services:
  - type: worker
    name: Bot-Wechter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python werchter.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    autoDeploy: true